version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/client'
    command: pnpm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - './client:/app/client'
      - '/app/client/node_modules'
    command: pnpm run dev
    depends_on:
      - backend

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
