version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/client'
    command: pnpm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
