@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsdnljcDFuazAwMDA5YWQ2eHdzbWZhMXMiLCJlbWFpbCI6InNvbWFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJzb21hIiwiY2FydCI6ImNsdnljcDFuazAwMDE5YWQ2eGRvcWJ3bGwiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcxNTI2NjEwNSwiZXhwIjoxNzE1MzUyNTA1fQ.2HrYPCYOQC9HoZ-l_WFkGviKS61F1flFMZwJww2zoyw
@port = 4000
//PRODUCT

GET http://localhost:{{port}}/product


###
GET http://localhost:{{port}}/product/clvocpvgr0000otxrzthzs5d6

###
POST http://localhost:{{port}}/product HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "title": "Thorns of Frost (Fae of Snow & Ice Book 2) ",
    "description": "When an arranged marriage is forced upon Ilara, she must find a way to outwit the Court of Winter in order to escape her demanded fate.",
    "author": "Krista Street",
    "stock": 17,
    "price": 15,
    "image": "https://m.media-amazon.com/images/I/91TZiJpNxuL._SL1500_.jpg"
}


### #! AUTH 

GET http://localhost:{{port}}/auth/profile HTTP/1.1
Authorization: {{token}}


###

POST http://localhost:{{port}}/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "test",
    "email": "test@text.com",
    "password": "123123"
}

###

POST http://localhost:{{port}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "test@text.com",
    "password": "123123"
}

### #! Metadata
POST http://localhost:{{port}}/metadata/add/asd
content-type: application/json

{
	"pages": 234,
	"publisher": "asdpub",
	"language": "esperanto",
	"cover": "PAPERBACK",
	"isbn": "ADWJKLHNÑAWJDAW"
}

###

PUT http://localhost:{{port}}/metadata/update/clvmvt81e00057nst8exhie8j
content-type: application/json

{
	"pages": 32
}


### !CART
GET http://localhost:{{port}}/cart HTTP/1.1
Authorization: {{token}}

###
POST http://localhost:{{port}}/cart/add/clvocrmeb000081xrbhbguz86 HTTP/1.1
Authorization: {{token}}

###
PATCH http://localhost:{{port}}/cart/qty/clvqs78fi0001546hixaxoef7 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"qty": -2
}

###
DELETE http://localhost:{{port}}/cart/del/clvofio8e0003cklaieuozi0u
Authorization: {{token}}




### REVIEWS

GET http://localhost:{{port}}/reviews/clvwq1kkv0002kk8fds4mvofs


###
POST http://localhost:{{port}}/reviews/send/clvwq1kkv0002kk8fds4mvofs
Content-Type: application/json
Authorization: {{token}}

{
	"stars": 5,
	"text": "good book "
}

###
PATCH http://localhost:{{port}}/reviews/update/clvpldezr0003r9et86o6fubb
Content-Type: application/json
Authorization: {{token}}

{
	"stars": 4
}

### 
DELETE http://localhost:{{port}}/reviews/del/clvpp9dat0001n12t4cwml86s
Authorization: {{token}}
