@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsd2YyZ3M3eTAwMDA2YmQ5b3BrZTZzZjYiLCJlbWFpbCI6InNvbWFAZ21haWwuY29tIiwidXNlcm5hbWUiOiJTb21hIiwiY2FydCI6ImNsd2YyZ3M4MTAwMDE2YmQ5Z3Jvb3N4bXQiLCJnZW1zIjoxMDAwLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3MTYyMzM0MzMsImV4cCI6MTcxNjMxOTgzM30.2xu0ceQ3ePjQufpahy2Up9R3UJIVhaBZL3347ZD3ae4
@port = 4000
//PRODUCT

GET http://localhost:{{port}}/product


###
GET http://localhost:{{port}}/product/clvocpvgr0000otxrzthzs5d6

###
POST http://localhost:{{port}}/product HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
	"title": "Harry Potter and the Philosopher's Stone",
	"description": "Turning the envelope over, his hand trembling, Harry saw a purple wax seal bearing a coat of arms; a lion, an eagle, a badger and a snake surrounding a large letter 'H'.\n\nHarry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
	"author": "J.K. Rowling",
	"stock": 23,
	"price": 7,
	"image": "https://m.media-amazon.com/images/I/81m9fP+LIPL._SL1500_.jpg"
}


### #! AUTH 

GET http://localhost:{{port}}/auth/profile HTTP/1.1
Authorization: {{token}}


###

POST http://localhost:{{port}}/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "soma",
    "email": "soma@gmail.com",
    "password": "123123"
}

###

POST http://localhost:{{port}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "soma@gmail.com",
    "password": "123123"
}

### #! Metadata
POST http://localhost:{{port}}/metadata/add/asd
content-type: application/json

{
	"pages": 234,
	"publisher": "asdpub",
	"language": "esperanto",
	"cover": "PAPERBACK",
	"isbn": "ADWJKLHNÑAWJDAW"
}

###

PUT http://localhost:{{port}}/metadata/update/clvmvt81e00057nst8exhie8j
content-type: application/json

{
	"pages": 32
}


### !CART
GET http://localhost:{{port}}/cart HTTP/1.1
Authorization: {{token}}

###
POST http://localhost:{{port}}/cart/add/clvwh523z0000kk8f2znrz2ux HTTP/1.1
Authorization: {{token}}

###
PATCH http://localhost:{{port}}/cart/qty/clvqs78fi0001546hixaxoef7 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"qty": -2
}

###
DELETE http://localhost:{{port}}/cart/del/clvofio8e0003cklaieuozi0u
Authorization: {{token}}




### REVIEWS

GET http://localhost:{{port}}/reviews/clwfd38rb0001109lhh08w4za?take=2&stars=3



###
POST http://localhost:{{port}}/reviews/send/clwfd38rb0001109lhh08w4za
Content-Type: application/json
Authorization: {{token}}

{
	"stars": 11,
	"text": "bad book s"
}

###
PATCH http://localhost:{{port}}/reviews/update/clvpldezr0003r9et86o6fubb
Content-Type: application/json
Authorization: {{token}}

{
	"stars": 4
}

### 
DELETE http://localhost:{{port}}/reviews/del/clvpp9dat0001n12t4cwml86s
Authorization: {{token}}


### ORDER

GET http://localhost:{{port}}/order
Authorization: {{token}}

###
GET http://localhost:{{port}}/order/clw86nhg30001k9hfk40qlcac
Authorization: {{token}}

###
POST http://localhost:{{port}}/order/create
Authorization: {{token}}

### stripe

GET http://localhost:{{port}}/stripe/customers
Authorization: {{token}}
